Repository LinioIT/common-symfony, pull requests merged in 2020-04, with the labels that each got.

#20 build: update symfony/templating to version 5
  composer.json
Labels: PR: partially-approved

#21 refactor: namespace for the templating bundle
  src/Controller/TemplatingAware.php
Labels: PR: partially-approved

#22 revert: namespace for the templating bundle
  src/Controller/TemplatingAware.php
Labels: PR: partially-approved

#23 fix: substitute deprecated renderResponse() with render()
  phpunit.xml.dist
  src/Controller/TemplatingAware.php
  tests/Controller/TemplatingAwareTest.php
Labels: PR: unreviewed

#24 build: update symfony/security-core requirement
  composer.json
Labels: PR: reviewed-approved
